apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: mysql-server
  ports:
  - protocol: TCP
    port: 3306  # Standard MySQL port
    targetPort: 3306
  type: ClusterIP