version: '3'

services:
  authservice:
    build: ./authenticationService
    ports:
      - "3000:3000"
    volumes:
      - ./authenticationService:/app
    networks:
      - school_mgmt_go_stack
    environment:
      mongoConnectionString: 'mongodb+srv://goku:mongoGoku56@schoolapp.jkesrkw.mongodb.net/'
      httpPort: 3000
      grpcPort: 5002
      tokenservice: 'tokenservice'
  notifyservice:
    build: ./notificationservice
    ports:
      - "3001:3001"
    volumes:
      - ./notificationservice:/app
    networks:
      - school_mgmt_go_stack
  tokenservice:
    build: ./tokenService
    ports:
      - "5002:5002"
    volumes:
      - ./tokenService:/app
    networks:
      - school_mgmt_go_stack
    environment:
      grpcPort: 5002
      secret: "djgfmjjdjshdytsajdghsjdgadgdvja234hcvdhcvsdc"

networks:
  school_mgmt_go_stack:
    driver: bridge