version: '4'

services:
  api:
    build: .
    ports: 
      - "3000:3000"
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: piyush
      MYSQL_PASSWORD: piyush
      MY_SQL_PORT: 3306
      MY_SQL_DATABASE: user
    volumes:
      - ./:/app
    networks:
      - authenticationService
    depends_on:
      - sql
  
  sql:
    image: mysql:latest
    networks:
      - authenticationService
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: piyush
      MYSQL_PASSWORD: piyush
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  authenticationService:
volumes:
  mysql_data:

