// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: authenticationServiceRpcServer/authenticationService.proto

package authenticationServiceRpcServer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenValidationClient is the client API for TokenValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenValidationClient interface {
	ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type tokenValidationClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenValidationClient(cc grpc.ClientConnInterface) TokenValidationClient {
	return &tokenValidationClient{cc}
}

func (c *tokenValidationClient) ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/authenticationServiceRpcServer.TokenValidation/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenValidationServer is the server API for TokenValidation service.
// All implementations must embed UnimplementedTokenValidationServer
// for forward compatibility
type TokenValidationServer interface {
	ValidateToken(context.Context, *TokenRequest) (*TokenResponse, error)
	mustEmbedUnimplementedTokenValidationServer()
}

// UnimplementedTokenValidationServer must be embedded to have forward compatible implementations.
type UnimplementedTokenValidationServer struct {
}

func (UnimplementedTokenValidationServer) ValidateToken(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedTokenValidationServer) mustEmbedUnimplementedTokenValidationServer() {}

// UnsafeTokenValidationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenValidationServer will
// result in compilation errors.
type UnsafeTokenValidationServer interface {
	mustEmbedUnimplementedTokenValidationServer()
}

func RegisterTokenValidationServer(s grpc.ServiceRegistrar, srv TokenValidationServer) {
	s.RegisterService(&TokenValidation_ServiceDesc, srv)
}

func _TokenValidation_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenValidationServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authenticationServiceRpcServer.TokenValidation/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenValidationServer).ValidateToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenValidation_ServiceDesc is the grpc.ServiceDesc for TokenValidation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenValidation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authenticationServiceRpcServer.TokenValidation",
	HandlerType: (*TokenValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _TokenValidation_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticationServiceRpcServer/authenticationService.proto",
}
