# ingress resource for protected services

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /mock_service
        pathType: Prefix
        backend:
          service:
            name: mock-service
            port:
              number: 3000
  nginx.ingress.kubernetes.io/auth-url: "http://authentication-service/jwt/v1/validate"

# ingress resource for un-protected services

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authenticate-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /authenticate
        pathType: Prefix
        backend:
          service:
            name: authentication-service
            port:
              number: 80
      