FROM golang:1.20.0

WORKDIR /app

COPY ./ /app/

RUN go mod download

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN go build -o tokenService

CMD air



